---
# tasks file for radiusconf
- name: Affichage echo
  debug:
    msg: "Welcomme to AAP 2"
- name: Copy du fichier azcopy
  ansible.builtin.copy:
    src: azcopy.exe
    dest: /home/rhel/
- name: Apllication du fichier de conf
  ansible.builtin.template:
    src: motd.j2
    dest: /home/rhel/motd.txt
